### PR TITLE
Removed qseeproxydaemon as it doesn't work under UT and causes battey…

### PR DESCRIPTION
**Pull request by Rargente**
… drain. Fixed scaling as per https://docs.ubports.com/en/latest/porting/running-ut.html#display-scaling .
The initial flash is far more functional now.

### CODE REVIEW

**Comment by Rargente** [comment]
@pbteja100 looking back I see there have been many changes to the scaling. Is there a reason you had it set so small? 
I feel 23 is the most useable and fits with the UT scaling advice.

**Comment by pbteja100** [comment]
@Rargente For the scaling part, There are less lags in switching apps when desktop mode is used (less browser freeze), the switch for it seems to appear only when in tablet UI and when GRID_UNIT_PX is set below 18

**Comment by Rargente** [comment]
Yes I see what you mean. The mode can be switched with the UTTT app even with the proper scaling.

**Comment by pbteja100** [comment]
@Rargente lets merge this later when we are able to stop other broken stuff which are also spamimg logs

**Comment by Rargente** [comment]
Sounds good. I'm working on a patch for the camera dumps.

**Pull request closed without merging**
